apiVersion: apps/v1
kind: Deployment
metadata:
  name: tts-api
  labels:
    app: tts-api
    env: production
spec:
  replicas: {{.Values.replicaCountApi}}
  selector:
    matchLabels:
      app: tts-api
  template:
    metadata:
      annotations:
        admission.datadoghq.com/python-lib.version: v1.7.1
        prometheus.io/port: "8082"
        prometheus.io/path: "/metrics"
        prometheus.io/scrape: "true"
      labels:
        app: tts-api
    spec:
      containers:
        - name: tts-api
          image: {{.Values.image.ttsapi}}
          imagePullPolicy: Always
          resources:
          ports:
            - containerPort: {{.Values.http.ttsport}}
          env:
            - name: DD_PROFILING_ENABLED
              value: "true"
            - name: DD_LOGS_INJECTION
              value: "true"
      restartPolicy: Always