apiVersion: apps/v1
kind: Deployment
metadata:
  name: tt-api
  labels:
    app: tt-api
    env: production
spec:
  replicas: {{.Values.replicaCountApi}}
  selector:
    matchLabels:
      app: tt-api
  template:
    metadata:
      annotations:
        prometheus.io/port: "8081"
        prometheus.io/path: "/metrics"
        prometheus.io/scrape: "true"
      labels:
        app: tt-api
    spec:
      containers:
        - name: tt-api
          image: {{.Values.image.ttapi}}
          imagePullPolicy: Always
          resources:
          ports:
            - containerPort: {{.Values.http.ttport}}
      restartPolicy: Always