apiVersion: apps/v1
kind: Deployment # type of resource
metadata:
  name: tt-api
  labels:
    app: tt-api
    env: production
spec:
  #replicas: {{.Values.deployment.replicas}}
  replicas: 2
  selector:
    matchLabels:
      app: tt-api
  template:
    metadata:
      #annotations:
        #prometheus.io/port: "5000"
        #prometheus.io/path: "/metrics"
        #prometheus.io/scrape: "true"
      labels:
        app: tt-api
    spec:
      containers:
        - name: tt-api
          image: melekelloumi/text_translation_api:latest
          #image: {{.Values.image.ttapi}}
          imagePullPolicy: Always
          resources:
          ports:
            #- containerPort: {{.Values.http.ttport}}
            - containerPort: 8081
      restartPolicy: Always