apiVersion: v1
kind: Service
metadata:
 name: tt-api-service
spec:
 selector:
  app: tt-api
 ports:
 - name: tt-api-port
   protocol: TCP
   port: {{.Values.http.ttport}}
   targetPort: {{.Values.http.ttport}}