apiVersion: apps/v1
kind: Deployment 
metadata:
  name: gtc-frontend
  labels: {{ toYaml .Values.labels | nindent 4 }}
spec:
  replicas: {{.Values.replicaCountFront}}
  selector:
    matchLabels:
      app: gtc-frontend
  template:
    metadata:
      labels:
        app: gtc-frontend
    spec:
      containers:
        - name: gtc-frontend
          image: {{.Values.image.frontend}}
          imagePullPolicy: Always
          resources:
          ports:
            - containerPort: {{.Values.http.frontendporttarget}}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{.Values.http.frontendporttarget}}
      restartPolicy: Always