apiVersion: v1
kind: Service
metadata:
 name: gtc-frontend-service
spec:
 selector:
  app: gtc-frontend
 ports:
 - name: gtc-frontend-port
   protocol: TCP
   port: {{.Values.http.frontendport}}
   targetPort: {{.Values.http.frontendporttarget}}