targetSystem: "linux"
clusterAgent:
  replicas: 2
  createPodDisruptionBudget: true
  admissionController:
    enabled: true
    mutateUnlabelled: true

datadog:
  site: us5.datadoghq.com

  kubelet: 
    tlsVerify: false

  logs:
    enabled: true
    containerCollectAll: true

  otlp:
    receiver:
      protocols:
        grpc:
          enabled: true
        http:
          enabled: true