name: CI/CD for Text Translation api
on:
  push:
    paths:
      - "TextTranslationAPI/**"
jobs:
  Build_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./TextTranslationAPI
          file: ./TextTranslationAPI/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/text_translation_api:latest